spring:
  datasource:
    url: jdbc:mysql://49.233.117.3:3306/test
    username: root
    password: mysql
    max-active: 2
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: fuxue-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: demo

nacos:
  config:
    server-addr: 127.0.0.1:8848